package main

import (
	"encoding/json"
	"fmt"
	"log"
	"math/rand"
	"net/http"
	"time"

	"github.com/google/uuid"
)

// DataRecord represents a single piece of data generated by our service.
type DataRecord struct {
	ID        string    `json:"id"`
	Value     int       `json:"value"`
	Timestamp time.Time `json:"timestamp"`
}

// healthCheckHandler returns a simple 200 OK for health checks.
func healthCheckHandler(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusOK)
	fmt.Fprintf(w, "OK")
}

// dataHandler creates and returns a new data record.
func dataHandler(w http.ResponseWriter, r *http.Request) {
	record := DataRecord{
		ID:        uuid.New().String(),
		Value:     rand.Intn(1000),
		Timestamp: time.Now().UTC(),
	}

	// Log the generated data to stdout to simulate processing
	log.Printf("Generated data record: ID=%s, Value=%d", record.ID, record.Value)

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusCreated)
	if err := json.NewEncoder(w).Encode(record); err != nil {
		log.Printf("Error encoding json response: %v", err)
	}
}

func main() {
	rand.Seed(time.Now().UnixNano())

	mux := http.NewServeMux()
	mux.HandleFunc("/health", healthCheckHandler)
	mux.HandleFunc("/api/v1/data", dataHandler)

	log.Println("Starting data generator server on :8080...")
	if err := http.ListenAndServe(":8080", mux); err != nil {
		log.Fatalf("Server failed to start: %v", err)
	}
}
